build&refactor: test 코드관련 devDependency 추가 & 컨벤션 수정
flitto/eslint-config-flitto-typescript pull request #13
Opened 2022-08-31 07:28 UTC by duarbdhks

### 주요 내용
* test 코드 동작 시, 필요한 devDependencies 추가
* 일부 컨벤션 수정

2022-08-31 09:57 UTC, dankang approved these changes

2022-09-05 01:15 UTC, coldMater requested changes

2022-09-05 01:15 UTC, coldMater commented on package.json
> +    "eslint-plugin-promise": "^6.0.1",
peer-dependency 에 해당하는 패키지는 추가해주지 않아도 될 것 같습니다.
확인 부탁드려요.

2022-09-05 01:15 UTC, coldMater commented on package.json
> +    "eslint-plugin-promise": "^6.0.1",
```suggestion
```

2022-09-05 01:15 UTC, coldMater commented on package.json
> +    "eslint-plugin-promise": "^6.0.1",
npm@8 버전부터는 peer-dependency 에 해당하는 패키지는 자동으로 설치됩니다.
```suggestion
```

2022-09-05 01:46 UTC, duarbdhks commented on package.json
> +    "eslint-plugin-promise": "^6.0.1",
제 PC 가 이상했나봐용

2022-09-05 02:41 UTC, coldMater approved these changes

2022-09-05 02:41 UTC, merged